# 1. no leading/trailing slash
# 2. `make validate_routes` for testing sample cases
# 3. add more pattern to handle optional trailing slash if rule is complex

#service1:
#  patterns:
#    - path/k1/(?P<v1>.*?)/k2/(?P<v2>.*?)
#  samples:
#    - path/k1/123/k2/xyz

#service2:
#  patterns:
#    - path/k1/int:v1/k2/alpha:v2
#  samples:
#    - path/k1/123/k2/xyz
#

image:
  patterns:
    - image
    - image/((?P<thumb_w>\d+)?x(?P<thumb_h>\d+)?/?)?/:filename
  samples:
    - image
    - image//image.jpg
    - image/100x/image.jpg
    - image/100x200/image.jpg
    - image/x/image.jpg

ping:
  patterns:
    - ping/alphanum:msg
  samples:
    - ping/test