default_chain:
    - RequestMaker
    - RequestMakerFile
    - Renderer
    - ResponseMaker
    - RequestMakerMongo
    - RequestParserJson

image_chain:
    - RequestMaker
    - RequestMakerFile
    - DecoratorAllowExternal
    - DecoratorNoRestPut
    - DecoratorNoRestDelete
    - Renderer
    - ResponseMaker
    - RestSourceImage
#image:
#    - Foo
# ------------------------------------------------------------------------------
# ping

#ping_chain:
#    - (no need)
ping:
    - PongNode
