default_chain:
    - RequestMaker
    - RequestMakerFile
    - Renderer
    - ResponseMaker
    - RequestMakerMongo
    - RequestParserJson

# ------------------------------------------------------------------------------
# ping

#ping_chain:
#    - (no need)
ping:
    - PongNode
